modLoader="javafml"
loaderVersion="[25,)"
logoFile="logo.png"

[[mods]]
	modId="defaultsettings" 
	version="${version}"
	displayName="DefaultSettings"
	description='''Keep your game's local settings in case of an update to your modpack'''
	authors="PT400C - Jomcraft Network"
	side="CLIENT"
	credits="Developed by Jomcraft Network"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/defaultsettings"
	updateJSONURL="https://gist.githubusercontent.com/PT400C/be22046792a7859688f655f1a5f83975/raw/"

[[dependencies.defaultsettings]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="CLIENT"
    
[[dependencies.defaultsettings]]
    modId="neptunefx"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"